In [1]:
import numdifftools

In [2]:
from algoritmo_simulazione_10 import algo_simulazione_10

In [3]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.simplefilter(action='ignore', category=DeprecationWarning)

In [ ]:
params, z, likelihood, iter = algo_simulazione_10(5000, 10, 30)

3.2979147105314474e-37
3.3042332165405413e-37
3.3042353893682022e-37
2.4874625184052422e-36
2.488725863114129e-36
2.4887258631775463e-36
2.4887263096492005e-36
2.489635011978059e-36
2.4896350119795017e-36
2.492378612838026e-36
4.488662404618863e-37
4.496883472613443e-37
4.496885754931349e-37
2.5688809668538363e-36
2.5703422465502685e-36
2.5703422466191624e-36
2.5703426536303002e-36
2.5713243775641584e-36
2.5713243775662896e-36
2.5739863559990307e-36
5.528276986642033e-37
5.538091144247361e-37
5.538093465615205e-37
2.586571009664454e-36
2.5881686397017354e-36
2.5881686397734443e-36
2.5881690110169315e-36
2.589187821337704e-36
2.589187821340476e-36
2.5917317240322356e-36
6.388614326862716e-37
6.399690021283464e-37
6.399692347678229e-37
2.5925933872569464e-36
2.5942817723000423e-36
2.5942817723730522e-36
2.5942821146878108e-36
2.5953184449278376e-36
2.5953184449311645e-36
2.597744728198895e-36
7.078185750417063e-37
7.090239855835923e-37
7.090242171016222e-37
2.5931331047123367e-36
2.59488

[0.86343 2.7651  1.66102]
D_triu
[[    nan 1.90167 0.79759]
 [    nan     nan 1.10408]
 [    nan     nan     nan]]
I move on to the check other masses
D_triu
[[    nan 1.90167     nan]
 [    nan     nan 1.10408]
 [    nan     nan     nan]]
I move on to the check other masses
D_triu
[[    nan 1.90167     nan]
 [    nan     nan     nan]
 [    nan     nan     nan]]
I move on to the check other masses
9.494574131241663e-37
9.508690677948454e-37
9.508692899549772e-37
2.1174691789294704e-36
2.1193376665009436e-36
2.1193376665737727e-36
2.119337923987179e-36
2.1203676539230885e-36
2.12036765392837e-36
2.1224055418973392e-36
[0.86503 2.76679 1.66264]
D_triu
[[    nan 1.90175 0.79761]
 [    nan     nan 1.10415]
 [    nan     nan     nan]]
I move on to the check other masses
D_triu
[[    nan 1.90175     nan]
 [    nan     nan 1.10415]
 [    nan     nan     nan]]
I move on to the check other masses
D_triu
[[    nan 1.90175     nan]
 [    nan     nan     nan]
 [    nan     nan     nan]]
I move on 

[ 1.28512 -0.00149  0.31716 -0.00149  1.2851   1.28512  1.2851 ]
D_triu
[[        nan 1.28661e+00 9.67962e-01 1.28661e+00 1.93793e-05 5.15168e-06
  2.37779e-05]
 [        nan         nan 3.18650e-01 7.98940e-08 1.28659e+00 1.28661e+00
  1.28659e+00]
 [        nan         nan         nan 3.18650e-01 9.67943e-01 9.67957e-01
  9.67939e-01]
 [        nan         nan         nan         nan 1.28659e+00 1.28661e+00
  1.28659e+00]
 [        nan         nan         nan         nan         nan 1.42276e-05
  4.39863e-06]
 [        nan         nan         nan         nan         nan         nan
  1.86262e-05]
 [        nan         nan         nan         nan         nan         nan
          nan]]
6.188199937894038e-46
6.616023424277042e-41
6.616023676585585e-41
4.776672059827716e-39
4.7766720607104454e-39
4.801406086385806e-39
4.8014060863858064e-39
4.801406091775762e-39
4.8014061208879864e-39
4.801406120888007e-39
[ 1.30306 -0.00149  0.3347   1.30304  1.30306  1.30304]
D_triu
[[        nan 1.30

[ 0.2777  -0.22233  2.08789  2.08793 -0.31437 -0.31435  1.25892 -0.31434]
D_triu
[[        nan 5.00027e-01 1.81019e+00 1.81023e+00 5.92071e-01 5.92053e-01
  9.81224e-01 5.92041e-01]
 [        nan         nan 2.31022e+00 2.31025e+00 9.20440e-02 9.20258e-02
  1.48125e+00 9.20139e-02]
 [        nan         nan         nan 3.41559e-05 2.40226e+00 2.40225e+00
  8.28970e-01 2.40223e+00]
 [        nan         nan         nan         nan 2.40230e+00 2.40228e+00
  8.29004e-01 2.40227e+00]
 [        nan         nan         nan         nan         nan 1.81939e-05
  1.57329e+00 3.01106e-05]
 [        nan         nan         nan         nan         nan         nan
  1.57328e+00 1.19167e-05]
 [        nan         nan         nan         nan         nan         nan
          nan 1.57326e+00]
 [        nan         nan         nan         nan         nan         nan
          nan         nan]]
8.432800958106536e-39
1.1632892683957488e-33
1.1632894430331152e-33
1.168694096763764e-33
1.1687319955454098e-

ISTOGRAMMI DEI PARAMETRI


In [ ]:
import numpy as np
import pandas as pd

In [ ]:
w = [0.4, 0.3, 0.3]
cluster = np.repeat(np.arange(1, len(w) + 1), [int(w[i] * 5000) for i in range(len(w))])

mean_1 = [-10,-10]
cov_1 = np.array([[0.7, 0.5], [0.5, 3]])
mean_2 = [0,0]
cov_2 = np.array([[2, -1], [-1, 3]])
mean_3 = [0,-12]
cov_3 = np.array([[0.5, 0.2], [0.2, 1]])

data_1 = np.random.multivariate_normal(mean_1, cov_1, int(w[0] * 5000))
data_2 = np.random.multivariate_normal(mean_2, cov_2, int(w[1] * 5000))
data_3 = np.random.multivariate_normal(mean_3, cov_3, int(w[2] * 5000))
data = np.vstack((data_1, data_2, data_3)) # combina i dati

data = pd.DataFrame(data, columns=['x1', 'x2'])

params_1_x1 = []
params_1_x2 = []
params_1_cat = []
params_2_x1 = []
params_2_x2 = []
params_2_cat = []
params_3_x1 = []
params_3_x2 = []
params_3_cat = []

for j in range(30):
  fitted_cluster = np.zeros(5000)
  for i in range(5000):
    fitted_cluster[i] = np.argmax(params[j]['z'][i]) + 1

  mean_real_1 = data[['x1','x2']][cluster==1].mean()
  mean_real_2 = data[['x1','x2']][cluster==2].mean()
  mean_real_3 = data[['x1','x2']][cluster==3].mean()
  mean_fitted_1 = data[['x1','x2']][fitted_cluster==1].mean()
  mean_fitted_2 = data[['x1','x2']][fitted_cluster==2].mean()
  mean_fitted_3 = data[['x1','x2']][fitted_cluster==3].mean()

  # cerco cluster corrispondente al cluster 1
  if np.linalg.norm(mean_real_1 - mean_fitted_1) < np.linalg.norm(mean_real_1 - mean_fitted_2) and np.linalg.norm(mean_real_1 - mean_fitted_1) < np.linalg.norm(mean_real_1 - mean_fitted_3):
    params_1_x1.append(params[j]['fix_param'][0][0])
    params_1_x2.append(params[j]['fix_param'][0][1])
    params_1_cat.append(params[j]['fix_param'][0][2])
  elif np.linalg.norm(mean_real_1 - mean_fitted_2) < np.linalg.norm(mean_real_1 - mean_fitted_1) and np.linalg.norm(mean_real_1 - mean_fitted_2) < np.linalg.norm(mean_real_1 - mean_fitted_3):
    params_1_x1.append(params[j]['fix_param'][1][0])
    params_1_x2.append(params[j]['fix_param'][1][1])
    params_1_cat.append(params[j]['fix_param'][1][2])
  else :
    params_1_x1.append(params[j]['fix_param'][2][0])
    params_1_x2.append(params[j]['fix_param'][2][1])
    params_1_cat.append(params[j]['fix_param'][2][2]) 

  # cerco cluster corrispondente al cluster 2
  if np.linalg.norm(mean_real_2 - mean_fitted_1) < np.linalg.norm(mean_real_2 - mean_fitted_2) and np.linalg.norm(mean_real_2 - mean_fitted_1) < np.linalg.norm(mean_real_2 - mean_fitted_3):
    params_2_x1.append(params[j]['fix_param'][0][0])
    params_2_x2.append(params[j]['fix_param'][0][1])
    params_2_cat.append(params[j]['fix_param'][0][2])
  elif np.linalg.norm(mean_real_2 - mean_fitted_2) < np.linalg.norm(mean_real_2 - mean_fitted_1) and np.linalg.norm(mean_real_2 - mean_fitted_2) < np.linalg.norm(mean_real_2 - mean_fitted_3):
    params_2_x1.append(params[j]['fix_param'][1][0])
    params_2_x2.append(params[j]['fix_param'][1][1])
    params_2_cat.append(params[j]['fix_param'][1][2])
  else :
    params_2_x1.append(params[j]['fix_param'][2][0])
    params_2_x2.append(params[j]['fix_param'][2][1])
    params_2_cat.append(params[j]['fix_param'][2][2]) 

  # cerco cluster corrispondente al cluster 3
  if np.linalg.norm(mean_real_3 - mean_fitted_1) < np.linalg.norm(mean_real_3 - mean_fitted_2) and np.linalg.norm(mean_real_3 - mean_fitted_1) < np.linalg.norm(mean_real_3 - mean_fitted_3):
    params_3_x1.append(params[j]['fix_param'][0][0])
    params_3_x2.append(params[j]['fix_param'][0][1])
    params_3_cat.append(params[j]['fix_param'][0][2])
  elif np.linalg.norm(mean_real_3 - mean_fitted_2) < np.linalg.norm(mean_real_3 - mean_fitted_1) and np.linalg.norm(mean_real_3 - mean_fitted_2) < np.linalg.norm(mean_real_3 - mean_fitted_3):
    params_3_x1.append(params[j]['fix_param'][1][0])
    params_3_x2.append(params[j]['fix_param'][1][1])
    params_3_cat.append(params[j]['fix_param'][1][2])
  else :
    params_3_x1.append(params[j]['fix_param'][2][0])
    params_3_x2.append(params[j]['fix_param'][2][1])
    params_3_cat.append(params[j]['fix_param'][2][2]) 


In [ ]:
simulazione = {'cluster1-x1': params_1_x1,
              'cluster1-x2': params_1_x2,
              'cluster1-catB': params_1_cat,
              'cluster2-x1': params_2_x1,
              'cluster2-x2': params_2_x2,
              'cluster2-catB': params_2_cat,
              'cluster3-x1': params_3_x1,
              'cluster3-x2': params_3_x2,
              'cluster3-catB': params_3_cat}
df = pd.DataFrame(simulazione)
df.to_csv('simulazione_1.csv', index=False)

In [ ]:
#PER LEGGERE IL FILE
file_path_1 = 'simulazione_1.csv'
file_path_2 = 'simulazione_2.csv'
file_path_3 = 'simulazione_3.csv'

# Read the CSV file into a DataFrame
sim_1 = pd.read_csv(file_path_1)
sim_2 = pd.read_csv(file_path_2)
sim_3 = pd.read_csv(file_path_3)

In [ ]:
dati = pd.concat([sim_1, sim_2, sim_3], axis=0, ignore_index=True)
params_1_x1 = dati['cluster1-x1']
params_1_x2 = dati['cluster1-x2']
params_1_cat = dati['cluster1-catB']
params_2_x1 = dati['cluster2-x1']
params_2_x2 = dati['cluster2-x2']
params_2_cat = dati['cluster2-catB']
params_3_x1 = dati['cluster3-x1']
params_3_x2 = dati['cluster3-x2']
params_3_cat = dati['cluster3-catB']

In [ ]:
import matplotlib.pyplot as plt
fig, axs = plt.subplots(1, 3, figsize=(12,8))
axs = axs.flatten()

axs[0].hist(params_1_x1, bins=17, edgecolor='black')
axs[0].axvline(x=2, color='red', linestyle='dashed', linewidth=2, label='Vertical Line at x=0')
axs[0].set_title('Histogram param x1 - cluster 1')

axs[1].hist(params_1_x2, bins=17, edgecolor='black')
axs[1].axvline(x=-0.4, color='red', linestyle='dashed', linewidth=2, label='Vertical Line at x=0')
axs[1].set_title('Histogram param x2 - cluster 1')

axs[2].hist(params_1_cat, bins=17, edgecolor='black')
axs[2].axvline(x=2, color='red', linestyle='dashed', linewidth=2, label='Vertical Line at x=0')
axs[2].set_title('Histogram param cat_B - cluster 1')

plt.savefig('Histogram params - cluster 1.png')


In [ ]:
fig, axs = plt.subplots(1, 3, figsize=(12,8))
axs = axs.flatten()

axs[0].hist(params_2_x1, bins=17, edgecolor='black')
axs[0].axvline(x=0.8, color='red', linestyle='dashed', linewidth=2, label='Vertical Line at x=0')
axs[0].set_title('Histogram param x1 - cluster 2')

axs[1].hist(params_2_x2, bins=17, edgecolor='black')
axs[1].axvline(x=-0.6, color='red', linestyle='dashed', linewidth=2, label='Vertical Line at x=0')
axs[1].set_title('Histogram param - cluster 2')

axs[2].hist(params_2_cat, bins=17, edgecolor='black')
axs[2].axvline(x=-2, color='red', linestyle='dashed', linewidth=2, label='Vertical Line at x=0')
axs[2].set_title('Histogram param cat_B - cluster 2')


plt.savefig('Histogram params - cluster 2.png')

In [ ]:
fig, axs = plt.subplots(1, 3, figsize=(12,8))
axs = axs.flatten()

axs[0].hist(params_3_x1, bins=17, edgecolor='black')
axs[0].axvline(x=-1.5, color='red', linestyle='dashed', linewidth=2, label='Vertical Line at x=0')
axs[0].set_title('Histogram param x1 - cluster 3')

axs[1].hist(params_3_x2, bins=17, edgecolor='black')
axs[1].axvline(x=-0.2, color='red', linestyle='dashed', linewidth=2, label='Vertical Line at x=0')
axs[1].set_title('Histogram param x2 - cluster 3')

axs[2].hist(params_3_cat, bins=17, edgecolor='black')
axs[2].axvline(x=-0.1, color='red', linestyle='dashed', linewidth=2, label='Vertical Line at x=0')
axs[2].set_title('Histogram param cat_B - cluster 3')


plt.savefig('Histogram params - cluster 3.png')

BOX-PLOT DEI PARAMETRI

In [ ]:
fig, axs = plt.subplots(1, 3, figsize=(12,8))
axs = axs.flatten()

axs[0].boxplot(params_1_x1)
axs[0].axhline(y=2, color='red', linestyle='--', linewidth=2, label='clust1-x1')
axs[0].set_title('Boxplot param x1 - cluster 1')

axs[1].boxplot(params_1_x2)
axs[1].axhline(y=-0.4, color='red', linestyle='--', linewidth=2, label='clust1-x1')
axs[1].set_title('Boxplot param x2 - cluster 1')

axs[2].boxplot(params_1_cat)
axs[2].axhline(y=2, color='red', linestyle='--', linewidth=2, label='clust1-x1')
axs[2].set_title('Boxplot param cat - cluster 1')


plt.savefig('Boxplot - cluster 1.png')

In [ ]:
fig, axs = plt.subplots(1, 3, figsize=(12,8))
axs = axs.flatten()

axs[0].boxplot(params_2_x1)
axs[0].axhline(y=0.8, color='red', linestyle='--', linewidth=2)
axs[0].set_title('Boxplot param x1 - cluster 2')

axs[1].boxplot(params_2_x2)
axs[1].axhline(y=-0.6, color='red', linestyle='--', linewidth=2)
axs[1].set_title('Boxplot param x2 - cluster 2')

axs[2].boxplot(params_2_cat)
axs[2].axhline(y=-2, color='red', linestyle='--', linewidth=2)
axs[2].set_title('Boxplot param cat - cluster 2')


plt.savefig('Boxplot - cluster 2.png')

In [ ]:
fig, axs = plt.subplots(1, 3, figsize=(12,8))
axs = axs.flatten()

axs[0].boxplot(params_3_x1)
axs[0].axhline(y=-1.5, color='red', linestyle='--', linewidth=2, label='clust1-x1')
axs[0].set_title('Boxplot param x1 - cluster 3')

axs[1].boxplot(params_3_x2)
axs[1].axhline(y=-0.2, color='red', linestyle='--', linewidth=2, label='clust1-x1')
axs[1].set_title('Boxplot param x2 - cluster 3')

axs[2].boxplot(params_3_cat)
axs[2].axhline(y=-0.1, color='red', linestyle='--', linewidth=2, label='clust1-x1')



plt.savefig('Boxplot - cluster 3.png')

In [ ]:
import pandas as pd

In [ ]:
valori_x1 = {'True params: x1' : [2, 1.8, -1.5],
             'Fitted params - Mean' : [np.mean(params_1_x1), np.mean(params_2_x1), np.mean(params_3_x1)],
             'Fitted params - Standard Deviation' : [np.std(params_1_x1),np.std(params_2_x1), np.std(params_3_x1)]
             }
parametri_x1 = pd.DataFrame(valori_x1)
parametri_x1

In [ ]:
valori_x2 = {'True params: x2' : [-0.4, -0.6, -0.4],
             'Fitted params - Mean' : [np.mean(params_1_x2), np.mean(params_2_x2), np.mean(params_3_x2)],
             'Fitted params - Standard Deviation' : [np.std(params_1_x2),np.std(params_2_x2), np.std(params_3_x2)]
             }
parametri_x2 = pd.DataFrame(valori_x2)
parametri_x2

In [ ]:
valori_cat = {'True params: cat_B' : [2, -2, -0.1],
             'Fitted params - Mean' : [np.mean(params_1_cat), np.mean(params_2_cat), np.mean(params_3_cat)],
             'Fitted params - Standard Deviation' : [np.std(params_1_cat),np.std(params_2_cat), np.std(params_3_cat)]
             }
parametri_cat = pd.DataFrame(valori_cat)
parametri_cat